
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/supabase'; // Fix: Updated import path to use the correct types file

const SUPABASE_URL = "https://zkrruihxszziifyogzko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprcnJ1aWh4c3p6aWlmeW9nemtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNjQ1NDksImV4cCI6MjA1ODc0MDU0OX0.ct3AMhbgnJg6pOjlACfwPR5n_Nz2pHX5AScfe84YM0U";

// Import the supabase client like this:
// import { supabase } from "@/lib/supabase/client";

// Create client with consistent configuration to ensure proper behavior
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      storage: localStorage
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    global: {
      headers: { 
        'x-application-name': 'hassleholmsif-p2014'
      },
    }
  }
);

// Check if Supabase is properly configured and connected
export const isSupabaseConfigured = async (): Promise<boolean> => {
  try {
    // Simple query to verify connection
    const { error } = await supabase
      .from('leagues')
      .select('id')
      .limit(1);
    
    return !error;
  } catch (err) {
    console.error("Error checking Supabase configuration:", err);
    return false;
  }
};

// Force a complete reset of the Supabase connection
export const forceResetConnection = async (): Promise<boolean> => {
  try {
    console.log("Forcing a complete reset of the Supabase connection...");
    
    // Clear all Supabase-related localStorage items
    const keysToRemove = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && (key.startsWith('sb-') || key.startsWith('supabase.auth'))) {
        keysToRemove.push(key);
      }
    }
    
    console.log(`Clearing ${keysToRemove.length} Supabase-related localStorage items`);
    keysToRemove.forEach(key => localStorage.removeItem(key));
    
    // Sign out from Supabase to clear any session state
    console.log("Signing out from Supabase...");
    await supabase.auth.signOut({ scope: 'global' });
    
    // Make a simple test query to check connection
    console.log("Testing new database connection...");
    const { error } = await supabase
      .from('leagues')
      .select('id')
      .limit(1);
    
    return !error;
  } catch (err) {
    console.error("Error during forced connection reset:", err);
    return false;
  }
};

// Initialize session immediately when this module is imported
(() => {
  try {
    console.log('Initializing Supabase connection...');
    
    // Schedule a delayed session refresh to avoid potential race conditions
    setTimeout(async () => {
      try {
        // Test database connection
        const { error } = await supabase
          .from('leagues')
          .select('id')
          .limit(1);
        
        if (!error) {
          console.log('Database connection test successful');
          // Cache successful connection
          localStorage.setItem('sb-connection-test', 'true');
        } else {
          console.error('Database connection test failed:', error);
        }
      } catch (err) {
        console.error('Error during initial connection check:', err);
      }
    }, 500);
  } catch (e) {
    console.error('Error during Supabase initialization:', e);
  }
})();
