
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/integrations/supabase/types';

const SUPABASE_URL = "https://zkrruihxszziifyogzko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprcnJ1aWh4c3p6aWlmeW9nemtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNjQ1NDksImV4cCI6MjA1ODc0MDU0OX0.ct3AMhbgnJg6pOjlACfwPR5n_Nz2pHX5AScfe84YM0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with explicit configuration to ensure consistent behavior
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    global: {
      headers: { 
        'x-application-name': 'hassleholmsif-p2014'
      },
    }
  }
);

// Check if Supabase is properly configured and connected
export const isSupabaseConfigured = async (): Promise<boolean> => {
  try {
    // First check if we have a session
    const { data: { session } } = await supabase.auth.getSession();
    
    // Try a simple query to verify connection
    const { error } = await supabase
      .from('leagues')
      .select('id')
      .limit(1);
    
    return !error;
  } catch (err) {
    console.error("Error checking Supabase configuration:", err);
    return false;
  }
};

// Initialize a Supabase session to ensure connection is established
export const initializeSupabaseSession = async (): Promise<boolean> => {
  try {
    // Check for existing session
    const { data: { session } } = await supabase.auth.getSession();
    
    if (session) {
      // Refresh the session if it exists
      await supabase.auth.refreshSession();
    }
    
    // Test connection with a simple query
    const { error } = await supabase
      .from('leagues')
      .select('id')
      .limit(1);
    
    if (!error) {
      // Cache successful connection
      localStorage.setItem('sb-connection-test', 'true');
      localStorage.setItem('sb-connection-test-time', Date.now().toString());
      return true;
    }
    
    return false;
  } catch (err) {
    console.error("Error initializing Supabase session:", err);
    return false;
  }
};

// Force a complete reset of the Supabase connection
export const forceResetConnection = async (): Promise<boolean> => {
  try {
    console.log("Forcing a complete reset of the Supabase connection...");
    
    // Clear all Supabase-related localStorage items
    const keysToRemove = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && (key.startsWith('sb-') || key.startsWith('supabase.auth'))) {
        keysToRemove.push(key);
      }
    }
    
    console.log(`Clearing ${keysToRemove.length} Supabase-related localStorage items`);
    keysToRemove.forEach(key => localStorage.removeItem(key));
    
    // Sign out from Supabase to clear any session state
    console.log("Signing out from Supabase...");
    await supabase.auth.signOut({ scope: 'global' });
    
    // Initialize a new session
    console.log("Testing new database connection...");
    return await initializeSupabaseSession();
  } catch (err) {
    console.error("Error during forced connection reset:", err);
    return false;
  }
};

// Force refresh session at app startup
(() => {
  try {
    console.log('Initializing Supabase connection...');
    
    // Schedule a delayed session refresh to avoid potential race conditions
    setTimeout(async () => {
      try {
        console.log('Checking for existing session...');
        const { data } = await supabase.auth.getSession();
        
        if (data.session) {
          console.log('Found existing session, refreshing tokens...');
          supabase.auth.refreshSession().then(({ data, error }) => {
            if (error) {
              console.error('Error refreshing session:', error);
            } else {
              console.log('Session refreshed successfully');
            }
          });
        } else {
          console.log('No existing session found');
        }
      } catch (err) {
        console.error('Error during initial session check:', err);
      }
    }, 500);
  } catch (e) {
    console.error('Error during Supabase initialization:', e);
  }
})();
