
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zkrruihxszziifyogzko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprcnJ1aWh4c3p6aWlmeW9nemtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNjQ1NDksImV4cCI6MjA1ODc0MDU0OX0.ct3AMhbgnJg6pOjlACfwPR5n_Nz2pHX5AScfe84YM0U";

// Import the supabase client like this:
// import { supabase } from "@/lib/supabase/client";

// Create client with explicit configuration to ensure consistent behavior
export const supabase = createClient(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      storage: localStorage
    }
  }
);

// Check if Supabase is properly configured and connected
export const isSupabaseConfigured = async (): Promise<boolean> => {
  try {
    // Simple query to verify connection
    const { error } = await supabase
      .from('leagues')
      .select('id')
      .limit(1);
    
    if (!error) {
      // Cache successful connection
      localStorage.setItem('sb-connection-test', 'true');
      localStorage.setItem('sb-connection-test-time', Date.now().toString());
      return true;
    }
    return !error;
  } catch (err) {
    console.error("Error checking Supabase configuration:", err);
    return false;
  }
};

// Force a complete reset of the Supabase connection
export const forceResetConnection = async (): Promise<boolean> => {
  try {
    // Clear all Supabase-related localStorage items
    const keysToRemove = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && (key.startsWith('sb-') || key.startsWith('supabase.auth'))) {
        keysToRemove.push(key);
      }
    }
    
    keysToRemove.forEach(key => localStorage.removeItem(key));
    
    // Sign out from Supabase to clear any session state
    await supabase.auth.signOut({ scope: 'global' });
    
    // Make a simple test query to check connection
    const { error } = await supabase
      .from('leagues')
      .select('id')
      .limit(1);
    
    return !error;
  } catch (err) {
    console.error("Error during forced connection reset:", err);
    return false;
  }
};
