
// This file is automatically generated. Do not edit it directly.
// This file is now a re-export of the lib/supabase/client.ts file to maintain backward compatibility

export { supabase, isSupabaseConfigured, forceResetConnection } from '@/lib/supabase/client';
